import Link from "next/link";
import styles from "./DevelopersPage.module.css";

export default function DevelopersPage(){return <main className={styles.page}>
  <section className={styles.hero}><div className={styles.wrap}><div className={styles.copy}><span>Для ЖК та забудовників</span><h1>Готове рішення<br/>для кожної <em>квартири.</em></h1><p>Серійні системи День-Ніч «Світлий льон» зі швидким кріпленням Gekko. Один колір, стандартні розміри та монтаж силами робітників, які вже працюють на об’єкті.</p><div className={styles.actions}><Link href="/become-dealer">Отримати тестовий комплект</Link><a href="#gekko">Як працює Gekko ↓</a></div><div className={styles.proof}><b>Без свердління</b><b>Серійна комплектація</b><b>Швидка заміна</b></div></div><div className={styles.image} role="img" aria-label="Система День-Ніч Світлий льон"><strong>GEKKO<small>швидке кріплення</small></strong></div></div></section>
  <section className={styles.section}><div className={styles.wrap}><header><span>Серійна комплектація</span><h2>Менше робіт.<br/>Більше передбачуваності.</h2><p>Рішення підходить для квартир, апартаментів, шоурумів і спільних просторів.</p></header><div className={styles.cards}><article><i>01</i><h3>Один універсальний колір</h3><p>«Світлий льон» пасує до білого, дерева, бетону та нейтральних інтер’єрів.</p></article><article><i>02</i><h3>Монтаж без окремої бригади</h3><p>Gekko встановлюється без свердління. Роботу може виконати персонал на об’єкті.</p></article><article><i>03</i><h3>Поставка партіями</h3><p>Маркування за корпусами, секціями, поверхами або квартирами.</p></article></div></div></section>
  <section className={styles.gekko} id="gekko"><div className={styles.wrap}><span>Логіка рішення</span><h2>Від тестового комплекту<br/>до всього об’єкта.</h2><div className={styles.steps}><article><b>01</b><h3>Тест</h3><p>Перевіряєте виріб і Gekko на типовому вікні.</p></article><article><b>02</b><h3>Специфікація</h3><p>Фіксуємо розміри, кількість, маркування й графік.</p></article><article><b>03</b><h3>Монтаж</h3><p>Робітники встановлюють вироби без профільного майстра.</p></article><article><b>04</b><h3>Поповнення</h3><p>Потрібний розмір легко замовити повторно.</p></article></div></div></section>
  <section className={styles.cta}><div className={styles.wrap}><div><span>Почніть із перевірки</span><h2>Отримайте тестовий комплект</h2><p>Перевірте Gekko та «Світлий льон» на типовому вікні.</p></div><Link href="/become-dealer">Запросити комплект</Link></div></section>
</main>}
